name: Elixir CI

on: [push, pull_request]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.18
      with:
        elixir-version: '1.16'
        otp-version: '26'
    - name: Restore dependencies cache
      uses: actions/cache@v4
      id: deps-cache
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Restore compiled dependencies cache
      uses: actions/cache@v4
      id: compiled-deps-cache
      with:
        path: _build/${{ env.MIX_ENV || 'dev'}}/lib
        key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-compiled-deps-cache-${{ env.MIX_ENV || 'dev' }}-${{ hashFiles('**/mix.lock','config/*.exs', 'mix.exs') }}
    - name: Install dependencies
      if: steps.deps-cache.outputs.cache-hit != 'true'
      run: mix deps.get
    - name: Compile Deps
      run: mix deps.compile
    - name: Compile App
      run: mix do clean, compile --warnings-as-errors
    - name: Run tests
      run: mix test --warnings-as-errors
    - name: Check formatting
      run: mix format --check-formatted
    - name: Check unused dependencies
      run: mix deps.unlock --check-unused
    - name: Clean before cache
      run: mix clean
